### ISSUE TITLE
Logo Project Enhancement

### ISSUE THREAD

**Issue by debpedrano** [hesabFun/ui#4]
Your project already has a logo but if you wanted to see mine, I would love to create a new logo that fits on the project that is more artistic and attractive.

**Comment by ErFUN-KH** [comment]
Well, I'm waiting for your logo.

**Comment by debpedrano** [comment]
@ErFUN-KH  Hello, I made two designs. since the current logo has shadow, I also made mine.

![image](https://user-images.githubusercontent.com/40510200/42119987-43b947be-7c46-11e8-84e1-1a6d34cef372.png)

**Comment by debpedrano** [comment]
@ErFUN-KH hello, since the current logo has a shadow. I also made mine. one with no shadow and one with shadow. and a Project Banner for ReadMe

![image](https://user-images.githubusercontent.com/40510200/42119996-7d1d1f80-7c46-11e8-9422-1efb3a3b4abe.png)

**Comment by debpedrano** [comment]
do you have any thoughts about your desired logo ? I can make some of it @ErFUN-KH

**Comment by ErFUN-KH** [comment]
Honestly, I'm not very good at art, I have no idea.

**Comment by debpedrano** [comment]
i will make another design , maybe i can change your mind and use my design. have a great day @ErFUN-KH  !

**Comment by ErFUN-KH** [comment]
Thanks, I'm waiting for you
@debpedrano

**Comment by ErFUN-KH** [comment]
Hi @debpedrano I spoke to my friends and they said your design is very good and artistic, so they gave me some notes to improve your work.
1- Please make the corners to be the curve in the chart.
2- The white logo is better than all of them, please continue with that.
3- If it's ok, give me several logos with different fonts spaciously in linear form.
4- Change circle green frame to square with curve corner like Instagram but lesser.
In the end, use your creativity for each part.

**Comment by debpedrano** [comment]
@ErFUN-KH  I will note those, thank you. i'll update my design as soon as I can finish it.

**Comment by ErFUN-KH** [comment]
Thank you, but that was not what I meant.
The middle circle must be bigger, the logo box must be square, also the chart is very rounded.

**Comment by debpedrano** [comment]
@ErFUN-KH  hmm okay, ill change it. thank you

**Comment by debpedrano** [comment]
sorry for the late response, I was so busy this past few days. I will make the design now and ill comment it here as soon as I am done. Thank you ! @ErFUN-KH

**Comment by debpedrano** [comment]
how about this one @ErFUN-KH 
![image](https://user-images.githubusercontent.com/40510200/43672815-683b3fbc-97e8-11e8-8e75-0398e4c3f67e.png)

**Comment by ErFUN-KH** [comment]
This is not what I wanted. I need to think more about it, can I tell you later?

**Comment by debpedrano** [comment]
@ErFUN-KH yes please, make some clarification about your desired logo. so that I can make It as soon as possible :) while waiting, I better make some new logos .

**Comment by debpedrano** [comment]
Hello, can I update this issue? Please leave a comment, thank you :) @ErFUN-KH

**Comment by ErFUN-KH** [comment]
Hi, I still have no idea, but I wrote this [description](https://about.hesabfun.com) about this project

**Comment by debpedrano** [comment]
I can enhance the current logo of the design, ill add some life on it.

**Comment by ErFUN-KH** [comment]
that's cool, this looks like a hand, can you change it a bit?

**Comment by debpedrano** [comment]
@ErFUN-KH 
how about this one?
![image](https://user-images.githubusercontent.com/40510200/46906823-0bef0000-cf3c-11e8-95ed-29328e834a61.png)

**Comment by ErFUN-KH** [comment]
Yes, that's great, thank a lot. please send a pull request.

**Comment by ErFUN-KH** [comment]
and

**Comment by debpedrano** [comment]
@ErFUN-KH , I will. Thank you so much!

**Comment by debpedrano** [comment]
@ErFUN-KH  Already sent a PR
